services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: has_eval_app
    volumes:
      - ./:/srv/app:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file:
      - .env.local
    depends_on:
      - db
    networks:
      - has_eval_net

  web:
    image: nginx:stable-alpine
    container_name: has_eval_web
    ports:
      - "8080:80"
    volumes:
      - ./:/srv/app:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - has_eval_net

  db:
    image: mariadb:10.11
    container_name: has_eval_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=has_eval
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony
    volumes:
      - has_eval_db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - has_eval_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: has_eval_phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=symfony
      - PMA_PASSWORD=symfony
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - has_eval_net


volumes:
  has_eval_db_data:

networks:
  has_eval_net:
    driver: bridge
